### ISSUE TITLE
mmap fails on WSL (linux too?)

### ISSUE THREAD

**Issue by cmp-nct** [cmp-nct/ggllm.cpp#13]
I've not looked deeper into it yet but we have a bt:
```
#0  __GI___mmap64 (offset=0, fd=10, flags=32769, prot=1, len=4963752448, addr=0x0) at ../sysdeps/unix/sysv/linux/mmap64.c:59
#1  __GI___mmap64 (addr=0x0, len=4963752448, prot=1, flags=32769, fd=10, offset=0) at ../sysdeps/unix/sysv/linux/mmap64.c:47
#2  0x0000564d9dd9e08c in llama_mmap::llama_mmap(llama_file*, unsigned long) ()
#3  0x0000564d9dd930d5 in falcon_model_load_internal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, falcon_context&, int, int, int, int, float const*, ggml_type, bool, bool, bool, void (*)(float, void*), void*) ()
#4  0x0000564d9dd94722 in falcon_init_from_file ()
#5  0x0000564d9dd6cf51 in falcon_init_from_gpt_params(gpt_params const&) ()
#6  0x0000564d9dd681c5 in main ()
```

Works fine when loading with --no-mmap

**Comment by cmp-nct** [comment]
Solved: mmap on WSL only works in native folders not on the /mnt/
Kinda ugly to have it stuck like that
